{% set version = '0.23-4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ttr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/TTR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TTR/TTR_{{ version }}.tar.gz
  sha256: eb17604da986213b3b924f0af65c3d089502a658a253ee34f6b8f6caccf6bfa2

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RUnit
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-curl
    - r-xts >=0.10_0
    - r-zoo

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-curl
    - r-xts >=0.10_0
    - r-zoo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('TTR')"           # [not win]
    - "\"%R%\" -e \"library('TTR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/joshuaulrich/TTR
  license: GPL-2
  summary: Functions and data to construct technical trading rules with R.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: TTR
# Type: Package
# Title: Technical Trading Rules
# Version: 0.23-4
# Author: Joshua Ulrich
# Maintainer: Joshua Ulrich <josh.m.ulrich@gmail.com>
# Imports: xts (>= 0.10-0), zoo, curl
# LinkingTo: xts
# Enhances: quantmod
# Suggests: RUnit
# Description: Functions and data to construct technical trading rules with R.
# License: GPL-2
# URL: https://github.com/joshuaulrich/TTR
# BugReports: https://github.com/joshuaulrich/TTR/issues
# NeedsCompilation: yes
# Packaged: 2018-09-20 11:28:00 UTC; josh
# Repository: CRAN
# Date/Publication: 2018-09-20 12:20:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
