travis:
  secure:
    BINSTAR_TOKEN: MmrMLPYRLKX6dCix8rB1MO2qaDJVJ6sSqQYUZpfW2AxcNqtcpOMYTjbVPUBlm1nItCDtUtvNZoqmAMmIKswNVdQWp+XGyxOPkuBUnYm50lL5GUeJwY9JcHaOhGkS5T94Hu/yKx87CT6Hi3KzpzHXn72MK1yajhwK88BdyNzkDSSUulQ6cHwfXKFq6KymItCRMW907LwZNjuFFZrjVT96cVhIHoq7kbmL2HU60zdTJvEgWzGiiJ3YBRybbQfPIvhqdTIJkTJ1mQZmB2CiulnywZ3Njpjpy1aC/yaT3QGVWPiqD9o7mx9S7jls1tc9RsCNoWeZ+kvmpP13fB3w6QITjUsqMBivYT0XH0s3NrQXfQGtQrZWjV5Gfj54KkmgZgEBnpqAMY2rr+fQArn5HypDgp1rbh+CS1uMHce+yPbqXzW0jNh9ZvBoo+BFQX5BKBMjgMH5DUOJwVXfJVTlxj6P0UKlSVHBHSfIJqH9j2B/4llMs7dXqX//c53MT0eXHyQj8ItZu8NjrmWbR5NawgVfdjsrvZ/1crrJ6NLUQJqrH7vDYCRpL98P/+fm1p0pJKV60dmDsuBNMint3h15+z1MINHjVDYVZ8Is2x5FQ5Mhdh45FlmGLUQ0+NmSVO1yXPL8FUq3oyATuy8dQwxC12jnCN7iCrUXlOwhVwn1WW1KKM8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
