travis:
  secure:
    BINSTAR_TOKEN: ncY8+1vcV2rB8Pilh+zxHSmvQDhslkPmWbOewJoqMpqNiRsW511N97P7bg2ezUf1K5FBYyid5NwvRbYMNHdfrV27WblgWxJBfbvzIz+0nf9GYmXPfm4XxybBcuTVyzo6tiCV8Y9C44XH26NaxLAngHuWb0GcKEXtH2NhP2M4O6eM7/6G3rxAr2BRjdy/SI0TVzysiXFdQPtBLs7p43nkK9uFYdAiyI9WcIzrBPkjva0AH83RX3ojG3afSKhdyJ2NZqAjBNiQNmYCcv1cGO4ilKux/jXQo7hXH2C9WEnMVivF+ZYGC3csKn9AxvBo+6Gsps9LzdMu1mOiv5uV/DkAy6RtiJEv3e/PCReHyIAn324NRlqmhNDSvDKk0i9UWOYiAkZ3JrL4XX26psi8oYRfuI73Nd4dWGmkYo6pJ5rHzAB7lIYzds5aWJ19GdxUjB8V1htIcgBR/ve2BfrEWBh8DFJGy9QY4DjRrLVneJSNgc46OQPBfsbLhdZF+Yeh6sib+Tp7FeFGujNOxUZ2CXBaRnv52XZbzWtvLpNW3KpXvsAUexsfFf4J47+Scwbi4woiDX9fXTb/KUiHA0qBkYQcRKSPc/VJHTmnOgzWuLILws6gRxf63suI+HObo0S6fyUPLjURzlZ5iuajOuDveA1ukqgoISAuoYRlRWdMgUkP5vo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
